### ISSUE TITLE
Empty array

### ISSUE THREAD

**Issue by fjoalland** [endroid/EndroidTwitterBundle#8]
Hi,

I have follow your instruction and it returns an empty array. I dont know because, if i change my consumer key by a false consum key, it returns an error => {"errors":[{"code":32,"message":"Could not authenticate you."}]}

**My controller :** 

`$twitter = $this->get('endroid.twitter');
        $response = $twitter->query('lists/list', 'GET', 'json');
        $tweets = json_decode($response->getContent() ,true);
        return $this->render('LTTwitterappBundle:Default:index.html.twig', array('message'=>$response->getContent()));`

**My twig :**  
`<body>
Liste des tweets:
{{ message }}
</body>`

And the result is an empty array => `List des tweets: []`

Can you help me ? 

Thanck you

**Comment by endroid** [comment]
Hi @fjoalland I think you need to specify the user_id as a parameter to define for what user you are retrieving the lists. When I create a list under my account I see it under https://twitter.com/<user_id>/lists and when I perform the following calls the list is returned.

$twitter = $this->get('endroid.twitter');
$response = $twitter->query('lists/list', 'GET', 'json', array('user_id' => ...);
$tweets = json_decode($response->getContent() ,true);
